name: Publish to Test-PyPI
run-name: ${{ github.actor }} publishing from ${{ github.ref }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install dependencies
        run: uv sync
      - name: Run pytest
        run: uv run -- pytest
      - name: Build package
        run: uv build
      - name: Store the distribution output
        uses: actions/upload-artifact@v4
        with:
          name: build-dist-folder
          path: dist/

  upload-to-test-pypi:
    runs-on: ubuntu-latest
    needs: build

    if: github.ref == 'refs/heads/main'

    environment:
      name: testpypi
      url: https://test.pypi.org/p/cepy-tools

    permissions:
      id-token: write

    steps:
      - name: Download dist folder
        uses: actions/download-artifact@v4
        with:
          name: build-dist-folder
          path: dist
      - name: Upload to test-pypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true

  upload-to-pypi:
    runs-on: ubuntu-latest
    needs: build

    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes

    environment:
      name: pypi
      url: https://pypi.org/p/cepy-tools

    permissions:
      id-token: write

    steps:
      - name: Download dist folder
        uses: actions/download-artifact@v4
        with:
          name: build-dist-folder
          path: dist
      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
